INSERT INTO product (name, description, cost, rrp) VALUES ('Card', 'This card is the superior card in a set of cards. If you play this card against a player with another card, you win instantly', 5, 30);
INSERT INTO product (name, description, cost, rrp) VALUES ('Spikeshoes', 'These shoes are made for the manliest of men. Use with caution', 50, 125);
INSERT INTO product (name, description, cost, rrp) VALUES ('Coffee', 'Intended for use when developing in Java and SQL. Do not drink too much', 1, 20);
INSERT INTO product (name, description, cost, rrp) VALUES ('Phone', 'The newest Nokia makes you the coolest kid in class', 2000, 3000);
INSERT INTO product (name, description, cost, rrp) VALUES ('Chair', 'Sit comfortably as a Java developer on this magnificent chair', 1, 200);
INSERT INTO product (name, description, cost, rrp) VALUES ('Laptop', 'Laptop 13" from Apple ', 7000, 13000);
INSERT INTO product (name, description, cost, rrp) VALUES ('Desktop Computer', 'A monster gaming computer', 1000, 20000);
INSERT INTO product (name, description, cost, rrp) VALUES ('Iron Maiden First CD', 'A classic CD from the classic band', 50, 130);
INSERT INTO product (name, description, cost, rrp) VALUES ('Computer Bag', 'Perfect for use in rainy weather conditions', 200, 500);
INSERT INTO product (name, description, cost, rrp) VALUES ('Notebook', 'Write down your whole life with this notebook', 70, 150);
INSERT INTO product (name, description, cost, rrp) VALUES ('Car', 'Great car suited for a business man', 10000, 500000);

INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("admin@admin","admin","admin","","","","","");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("sven@mail.se","sven","Sven","Janson","383-8726 Tempor Avenue","08628-727","Perwez","1-385-461-6140");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("dictum.placerat.augue@nullaatsem.org","Duis","Gabriel","Herrera","623-5456 Fermentum Rd.","1627HP","Lauregno/Laurein","1-558-565-9706");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("eget.volutpat@urnaNunc.com","nisl.","Fiona","Wilson","396-4191 Parturient Street","C3B 8W6","CÃ¡diz","1-718-813-7921");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Phasellus@vulputateposuere.co.uk","erat","Jason","Dominguez","P.O. Box 808, 9853 Interdum Avenue","WQ2O 7SS","Merthyr Tydfil","1-853-740-5031");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("ultrices.a.auctor@amet.com","ornare","Martena","Boone","Ap #383-8640 Velit. Road","4270","Cumberland","1-969-956-8642");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("montes.nascetur@imperdietdictummagna.edu","lacus.","Regan","King","5823 In, Ave","2053ZV","Borgomasino","1-568-828-8306");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("libero@Vivamus.ca","Ut","Bertha","Wood","Ap #739-5342 Ut Av.","51598","Orosei","1-651-629-6551");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("sapien.gravida@dolorquamelementum.net","nulla","Stella","Newton","9962 Lectus. Ave","48410","Fort Smith","1-478-103-7148");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("dui.nec@faucibusorciluctus.co.uk","natoque","Judith","Mcgowan","494-2933 Consectetuer Road","18447","New Galloway","1-948-706-6813");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("lorem@antebibendumullamcorper.com","dolor.","Cherokee","Blackwell","P.O. Box 775, 7486 Per Rd.","20125","Deschambault","1-815-525-0097");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("et@vehiculaPellentesque.net","tincidunt","Flynn","Conrad","947-4335 Nunc Road","4905","Souvret","1-695-667-4044");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("velit@ut.org","dui.","Vance","Hines","104-5385 Et, Avenue","8080","Staï¿½furt","1-910-242-5638");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("euismod@ametornarelectus.co.uk","malesuada","Wallace","Abbott","Ap #487-6174 Placerat Rd.","2429YL","Aguacaliente (San Francisco)","1-204-712-6022");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("orci.luctus.et@eu.org","pharetra,","Ifeoma","Guerra","7432 Pede, Avenue","1882","Cerami","1-862-312-1678");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("elit.pellentesque@sociosquadlitora.net","scelerisque","Basil","Mccullough","4426 Lobortis St.","Q9 3WZ","Dampicourt","1-281-327-7110");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("sem@felisadipiscingfringilla.ca","egestas.","Lars","Hodge","5481 Nunc St.","41873-038","South Burlington","1-520-490-7190");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tempor.augue@nuncullamcorper.net","non,","Sage","Price","Ap #918-4418 Lacus St.","5611EM","Columbus","1-823-575-6113");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("in.sodales@acfermentum.co.uk","eu,","Ezra","Shaffer","Ap #921-9210 Luctus Av.","76118","Limbach-Oberfrohna","1-155-395-3308");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Sed@ullamcorperDuiscursus.org","Nulla","Halla","Boyd","Ap #638-5824 Urna, Av.","6597","Fontaine-l'Evï¿½que","1-898-259-9389");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("lorem.vehicula.et@rutrumjusto.edu","tempus,","Lionel","Duffy","P.O. Box 784, 1420 Lorem Av.","2396","Koblenz","1-642-392-8748");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("lorem.eget.mollis@orciPhasellus.edu","ac","Lamar","Cannon","272-5669 Vulputate, St.","RB76 5DK","Gresham","1-331-949-4076");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("netus@Nullafacilisis.net","sit","Rafael","Roberts","6846 Faucibus Rd.","5706","South Bend","1-639-635-7827");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("erat@Nullam.edu","vitae","Colleen","Reed","P.O. Box 235, 5957 In Avenue","4705","Lac La Biche County","1-240-569-9048");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("eget.mollis@Cras.co.uk","pede","Benjamin","Harrington","6093 Bibendum. St.","70653","Columbia","1-704-765-9749");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("aliquet.magna.a@pulvinar.edu","dictum","Eric","Beach","P.O. Box 618, 3768 Venenatis Street","33728","Forres","1-594-604-2973");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("elementum@parturientmontesnascetur.edu","Duis","Chaim","Fleming","7382 Mollis Rd.","L5C 3S0","Cartagena","1-878-842-0631");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Nam@tincidunt.ca","quis","Murphy","Baxter","Ap #837-8653 Lectus. Road","Y6 3UQ","Sint-Kruis-Winkel","1-766-735-4939");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("eget.metus@hendrerit.net","fermentum","Ronan","Day","206-4089 Dignissim Av.","75471","Wokingham","1-862-521-3198");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("et@sodales.net","adipiscing","Rosalyn","Snider","P.O. Box 560, 1432 Tempor St.","NF4C 5ZF","East Gwillimbury","1-609-973-7236");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tortor.Integer.aliquam@amalesuada.co.uk","arcu.","Ferdinand","Gilbert","Ap #415-9915 Sapien, Avenue","38166-542","Inuvik","1-334-167-3480");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("pretium@purusin.net","dignissim","Xena","Hobbs","Ap #845-521 Ac Street","54972","Laval","1-890-290-1683");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Fusce@Integer.edu","scelerisque","Lucy","Joyner","431-7639 Lacinia Ave","92346","Stilo","1-858-925-3788");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("metus@eutellus.org","odio.","Keely","Dejesus","1740 Arcu. Road","T3J 1V9","Saint-Malo","1-289-581-8856");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("suscipit.est.ac@Phasellusdapibus.net","eget","Tara","Navarro","723-4270 Vivamus Rd.","87505","Portigliola","1-947-455-7169");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("In.at.pede@sitamet.org","amet,","Harriet","Reilly","5891 Maecenas Road","4700HZ","Wolfurt","1-717-294-5147");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("accumsan.laoreet@acmetus.edu","eleifend","Graiden","Pate","Ap #272-9110 Aliquam Road","54552","Stene","1-836-658-4289");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("euismod@orciquislectus.net","Pellentesque","Nash","Neal","Ap #427-1698 Tortor. St.","8205FS","Ceranesi","1-446-448-7834");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("dui.Fusce.diam@In.net","lobortis","Rhea","Mooney","P.O. Box 540, 4381 Augue Rd.","5450","Hertford","1-834-840-6603");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Cras@ligula.ca","Cum","Aurelia","Montoya","5068 Natoque Road","61153","Borriana","1-425-437-1809");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("nisl@convallis.net","mollis","Ahmed","Taylor","P.O. Box 608, 6504 Erat Rd.","50187","March","1-255-696-9713");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tempor@eget.net","arcu","Rajah","Prince","477-7227 Est, Av.","8788","Avise","1-377-608-6422");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tellus@Donecconsectetuer.edu","accumsan","Tanner","Vasquez","P.O. Box 963, 9107 Lorem Road","16083-282","Moricone","1-547-380-3918");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("adipiscing.ligula.Aenean@vulputate.net","odio.","Palmer","Wall","Ap #416-9390 Est Ave","41950-441","Neerharen","1-993-370-2081");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("est.vitae@nunc.edu","Aenean","Baxter","Wise","352-7700 Aliquet St.","73349","Merksplas","1-390-148-2852");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("libero.Proin@justoProin.com","cubilia","Nehru","Wiggins","529-8238 Vivamus Rd.","06772","Hastings","1-943-148-0446");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("pretium.aliquet.metus@nibhAliquam.edu","aliquet.","Medge","Wong","Ap #920-1119 Augue. St.","Y6S 6KO","Acquasparta","1-653-538-8735");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Fusce@nequeNullamnisl.net","turpis","Maite","Morin","P.O. Box 781, 4450 Nonummy Av.","76363","Jerez de la Frontera","1-771-273-0288");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("risus.quis@semNulla.co.uk","vulputate","Daphne","Rhodes","993-3177 Non, St.","8399","Moorsel","1-249-296-4564");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("vel.venenatis@Aliquamauctorvelit.edu","Quisque","Cheryl","Henry","Ap #268-6214 Gravida Road","9047","Osimo","1-902-757-1703");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("aliquet.libero.Integer@fermentum.ca","auctor","Martena","Newman","Ap #607-5656 Vitae, Rd.","T0P 3P8","Stewart","1-159-573-8979");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("ac.arcu.Nunc@Vestibulum.com","eget,","Yvonne","Maynard","Ap #938-6870 Porta Street","V05 7JZ","Ravenstein","1-739-801-3099");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Curae@diamdictum.co.uk","auctor,","Gay","Dillard","331-3880 Tincidunt Street","4135EG","Wanneroo","1-343-373-7361");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("cursus.Nunc@convallisantelectus.com","quis","Denise","Dotson","313 Et Rd.","4278XR","Sint-Pieters-Kapelle","1-718-515-6761");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Nullam.lobortis@ipsumnuncid.com","nascetur","Inga","Orr","6937 Vitae Road","8733","Klemskerke","1-590-753-3131");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Proin.nisl.sem@egetmollis.com","tincidunt.","Dara","Alvarez","P.O. Box 214, 7106 Non St.","9104","Kitimat","1-477-781-4747");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("ligula.Nullam.feugiat@ipsumprimis.com","Curabitur","Eleanor","Ramos","989-9369 Etiam St.","1673","Blehen","1-129-721-2838");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("magnis.dis@sitamet.com","cursus","Patricia","Leblanc","1029 Mauris Road","76280","Leernes","1-298-658-2282");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("lacus@egetipsum.com","erat.","Lael","Carrillo","P.O. Box 218, 1328 Velit. Street","P8T 9N3","Legal","1-337-969-7540");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tempus.non.lacinia@ipsum.org","Vivamus","Regan","Langley","9040 Aliquam St.","1713","Annan","1-356-388-2555");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Suspendisse.sed@erosnectellus.edu","nisi","Charity","Herring","Ap #629-8701 Et St.","22908","Gloucester","1-246-700-6958");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tristique.senectus.et@nequeNullamnisl.org","orci","Anjolie","Mercado","P.O. Box 414, 1193 Non Street","1775TI","Drongen","1-482-568-8240");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("magna.Ut@perinceptos.ca","nec","Maite","Jenkins","Ap #590-8382 Nec, St.","AX9N 7SV","Pace del Mela","1-768-623-5656");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("nascetur.ridiculus@telluseuaugue.org","Aliquam","Daquan","Evans","Ap #855-4499 Egestas. Avenue","95961-515","San Lorenzo","1-350-804-4240");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("ac.arcu@iaculisodio.co.uk","quam","Eugenia","Hawkins","P.O. Box 513, 1654 Cursus St.","4563MR","Grand Island","1-553-735-7618");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("ut.dolor@Aliquamnec.com","elit","Clayton","Nguyen","Ap #149-7357 Proin Street","1513","Port Hope","1-392-510-3011");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("facilisis@pellentesquemassalobortis.edu","et,","Yvonne","Mccormick","543-8364 At St.","6668YW","Castelluccio Valmaggiore","1-777-112-2274");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("nunc.sed@interdum.com","inceptos","Regan","Spence","P.O. Box 537, 4449 Arcu St.","67305","Abolens","1-588-624-0489");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("fringilla.est.Mauris@IncondimentumDonec.edu","nec,","Cadman","Mcknight","Ap #708-6169 Varius St.","92774","Cartagena","1-920-948-9080");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("at.lacus@ligulaAenean.com","nulla","Germaine","Carey","900-7203 Etiam St.","VZ17 5BJ","Madrid","1-490-410-8364");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("nulla.magna.malesuada@semsempererat.ca","tristique","Courtney","Hodge","752-6317 Adipiscing Rd.","9032SA","Gravilias","1-315-458-3031");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tellus.sem@neque.com","cursus","Deacon","Bond","Ap #967-4609 Interdum. Rd.","19789","Ourense","1-170-481-4851");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("magna.malesuada@vitaeorci.com","hymenaeos.","Melanie","Alvarez","726-8047 Duis Ave","66928","Otricoli","1-663-242-9238");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tincidunt@Duisat.net","sagittis.","Kuame","Reeves","Ap #848-9051 Diam Ave","2942","Noragugume","1-978-832-0148");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("pharetra.Nam@eleifendCrassed.ca","lorem.","Desirae","Velazquez","726-201 Donec Av.","97902","Guardia Sanframondi","1-542-495-7697");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("malesuada@etnetuset.co.uk","semper","Malik","Kirkland","365-7288 Ornare St.","8692","Casacalenda","1-429-707-8852");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("ornare.Fusce@lobortis.org","mi","Celeste","Daugherty","910-4865 Metus. St.","11414","AlenÃ§on","1-281-837-3442");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("malesuada.augue.ut@mi.org","dolor.","Nicholas","Lawson","783-5113 Libero Rd.","3016","Wabamun","1-715-105-6792");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("aliquet.sem.ut@convallisante.edu","nisl.","Joelle","Parrish","P.O. Box 674, 7511 Fusce Av.","YS93 8IP","Brugge Bruges","1-150-894-3837");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("eget@magna.co.uk","elementum,","Brock","Lawson","3484 Nascetur Avenue","8977FL","Ortonovo","1-335-781-9448");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Nam@liberolacusvarius.edu","pede","Sean","Rojas","Ap #388-3086 Dui. Road","9486","Meridian","1-185-268-7333");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("accumsan.neque.et@euodio.net","netus","Octavia","Franklin","Ap #262-1408 Tincidunt Road","72274","Brixton","1-285-288-1154");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("mollis@pulvinar.co.uk","dictum.","Chester","Hoover","518-5356 Faucibus Rd.","30507","Hearst","1-969-750-7169");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("tincidunt.congue.turpis@ametnulla.edu","ipsum.","Belle","Summers","9175 Aliquam Ave","48185","Shawinigan","1-470-246-8626");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("sed.sapien.Nunc@enim.org","Proin","Signe","Barron","P.O. Box 737, 8589 Metus St.","4730","Scanzano Jonico","1-408-422-4219");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("semper.dui.lectus@erosnectellus.org","dolor","Wang","Bennett","P.O. Box 161, 3647 Diam. Av.","73859","Neerglabbeek","1-207-294-8733");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Nunc@lacusCras.edu","ullamcorper,","Deacon","Cabrera","Ap #562-5428 Ultricies Ave","J2T 0E8","Gaithersburg","1-406-662-8775");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Fusce.fermentum@nibhlaciniaorci.com","nec","Cleo","Gay","P.O. Box 643, 7554 Magna. Av.","7793MR","Lille","1-766-267-8221");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("fringilla@tellusNunc.org","blandit","Geoffrey","Combs","P.O. Box 151, 2278 Donec Road","6904","Midlands","1-934-217-9376");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("eleifend@tellusnon.com","dictum.","Madaline","Holder","3825 Amet Av.","2982","Johnstone","1-431-256-7928");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Aliquam.auctor@hymenaeosMauris.edu","vestibulum.","Charde","Lawson","P.O. Box 998, 2494 Varius. St.","R6K 5G7","Itapipoca","1-738-677-8171");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("neque.vitae.semper@porttitortellus.edu","venenatis","Erich","Boyd","Ap #789-5026 Et St.","8933","La Magdeleine","1-105-543-0582");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("odio.Nam.interdum@amifringilla.co.uk","vel","Virginia","Phelps","Ap #470-9801 Lectus St.","3784","Narcao","1-838-710-7152");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("arcu.vel@aliquetlibero.co.uk","non","Casey","Lowery","827-4288 Sollicitudin Street","65571","Town of Yarmouth","1-477-368-6751");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("molestie.dapibus@maurissit.org","ligula","Avye","Stuart","P.O. Box 527, 5750 Id Av.","25732","Paulatuk","1-371-358-8513");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("urna@atlibero.ca","sollicitudin","Ishmael","Mccullough","7457 Urna St.","4878","West Valley City","1-925-470-5035");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Nam@tempus.co.uk","in","Isaiah","Gilliam","P.O. Box 923, 458 Convallis Ave","Y3P 2XD","Grangemouth","1-406-804-8825");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("turpis.vitae.purus@nec.co.uk","dui","Steel","Alexander","P.O. Box 242, 5492 Gravida. St.","70258","Waitakere","1-857-847-7942");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Ut.tincidunt@Crasdolor.co.uk","Etiam","Elvis","Garrison","Ap #800-5017 Phasellus Rd.","H5P 4E8","Kitimat","1-472-954-5562");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("Etiam@consectetuermaurisid.net","aliquet.","Chantale","Stephenson","P.O. Box 994, 5604 Risus. Avenue","31580","Builth Wells","1-406-130-9088");
INSERT INTO user (email,password,firstname,surname,streetAddress,postcode,town,phonenumber) VALUES ("ac.mattis.semper@nonummy.co.uk","nec","Dane","Dean","Ap #208-3615 Aliquam Rd.","6025OZ","Langford","1-186-814-0653");

INSERT INTO category (name, staffId) VALUES ('Books', 27);
INSERT INTO category (name, staffId) VALUES ('Computing', 58);
INSERT INTO category (name, staffId) VALUES ('Toys', 62);
INSERT INTO category (name, staffId) VALUES ('Gardening', 63);
INSERT INTO category (name, staffId) VALUES ('Electronics', 58);
INSERT INTO category (name, staffId) VALUES ('Clothes', 63);
INSERT INTO category (name, staffId) VALUES ('Mens', 63);
INSERT INTO category (name, staffId) VALUES ('Womens', 63);
INSERT INTO category (name, staffId) VALUES ('Children', 63);
INSERT INTO category (name, staffId) VALUES ('Sports & Outdoors', 71);
INSERT INTO category (name, staffId) VALUES ('Films', 27);

INSERT INTO category_product (products_id, category_id) VALUES (7, 2);
INSERT INTO category_product (products_id, category_id) VALUES (7, 3);
INSERT INTO category_product (products_id, category_id) VALUES (11, 3);
INSERT INTO category_product (products_id, category_id) VALUES (1, 3);
INSERT INTO category_product (products_id, category_id) VALUES (2, 10);
INSERT INTO category_product (products_id, category_id) VALUES (3, 10);
INSERT INTO category_product (products_id, category_id) VALUES (4, 5);
INSERT INTO category_product (products_id, category_id) VALUES (5, 4);
INSERT INTO category_product (products_id, category_id) VALUES (5, 10);
INSERT INTO category_product (products_id, category_id) VALUES (6, 2);
INSERT INTO category_product (products_id, category_id) VALUES (6, 5);
INSERT INTO category_product (products_id, category_id) VALUES (8, 11);
INSERT INTO category_product (products_id, category_id) VALUES (8, 3);
INSERT INTO category_product (products_id, category_id) VALUES (9, 2);
INSERT INTO category_product (products_id, category_id) VALUES (10, 1);

INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (1, 2, 2);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (1, 3, 1);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (1, 4, 5);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (2, 5, 2);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (2, 3, 3);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (2, 6, 1);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (5, 3, 10);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (20, 7, 2);
INSERT INTO ProductsInCart (user_id, product_id, quantity) VALUES (20, 8, 10);
